[package]
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
build = 'build.rs'
description = 'A fresh FRAME-based Substrate node, ready for hacking.'
edition = '2018'
homepage = 'https://substrate.dev'
license = 'Unlicense'
name = 'mv-node'
repository = 'https://github.com/substrate-developer-hub/substrate-mv-node/'
version = '3.0.0'

[[bin]]
name = 'mv-node'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-build-script-utils = '3.0.0'

[dependencies]
jsonrpc-core = '15.1.0'
structopt = '0.3.8'
codec = { package = 'parity-scale-codec', version = '2.0.0' }
log = "0.4"
serde = { version = "1.0", features = ["derive"]}

# Substrate dependencies
frame-benchmarking = { version = '3.1.0', git = 'http://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
frame-benchmarking-cli = { version = '3.0.0', git = 'http://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
pallet-transaction-payment-rpc = { version = '3.0.0', git = 'http://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sc-basic-authorship = { version = '0.9.0', git = 'http://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sc-cli = { version = '0.9.0', git = 'http://github.com/paritytech/substrate.git', branch = 'rococo-v1', features = ['wasmtime'] }
sc-client-api = { version = '3.0.0', git = 'http://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sc-consensus = { version = '0.9.0', git = 'http://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sc-consensus-aura = { version = '0.9.0', git = 'http://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sc-executor = { version = '0.9.0', git = 'http://github.com/paritytech/substrate.git', branch = 'rococo-v1', features = ['wasmtime'] }
sc-finality-grandpa = { version = '0.9.0', git = 'http://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sc-keystore = { version = '3.0.0', git = 'http://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sc-rpc = { version = '3.0.0', git = 'http://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sc-rpc-api = { version = '0.9.0', git = 'http://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sc-service = { version = '0.9.0', git = 'http://github.com/paritytech/substrate.git', branch = 'rococo-v1', features = ['wasmtime'] }
sc-telemetry = { version = '3.0.0', git = 'http://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sc-transaction-pool = { version = '3.0.0', git = 'http://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sp-api = { version = '3.0.0', git = 'http://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sp-block-builder = { version = '3.0.0', git = 'http://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sp-blockchain = { version = '3.0.0', git = 'http://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sp-consensus = { version = '0.9.0', git = 'http://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sp-consensus-aura = { version = '0.9.0', git = 'http://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sp-core = { version = '3.0.0', git = 'http://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sp-finality-grandpa = { version = '3.0.0', git = 'http://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sp-inherents = { version = '3.0.0', git = 'http://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sp-runtime = { version = '3.0.0', git = 'http://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sp-transaction-pool = { version = '3.0.0', git = 'http://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sp-trie = { version = '3.0.0', git = 'http://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sc-tracing = { version = '3.0.0', git = 'http://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sp-timestamp = { version = '3.0.0', git = 'http://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sc-chain-spec = { version = '3.0.0', git = 'http://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
substrate-frame-rpc-system = { version = '3.0.0', git = 'http://github.com/paritytech/substrate.git', branch = 'rococo-v1' }

# Cumulus
cumulus-client-consensus-relay-chain = { git = 'http://github.com/paritytech/cumulus.git', branch = 'rococo-v1' }
cumulus-client-network = { git = 'http://github.com/paritytech/cumulus.git', branch = 'rococo-v1' }
cumulus-client-service = { git = 'http://github.com/paritytech/cumulus.git', branch = 'rococo-v1' }
cumulus-client-cli = { git = 'http://github.com/paritytech/cumulus.git', branch = 'rococo-v1' }
cumulus-primitives-core = { git = 'http://github.com/paritytech/cumulus.git', branch = 'rococo-v1' }

# Polkadot
polkadot-primitives = { git = 'http://github.com/paritytech/polkadot.git', branch = 'rococo-v1' }
polkadot-service = { git = 'http://github.com/paritytech/polkadot.git', branch = 'rococo-v1' }
polkadot-cli = { git = 'http://github.com/paritytech/polkadot.git', branch = 'rococo-v1' }
polkadot-parachain = { git = 'http://github.com/paritytech/polkadot.git', branch = 'rococo-v1' }

# Local dependencies
mv-node-runtime = { path = '../runtime', version = '3.0.0' }
sp-mvm-rpc = { path = '../pallets/sp-mvm/rpc' }
sp-mvm-rpc-runtime = { path = '../pallets/sp-mvm/rpc/runtime' }

[features]
default = []
runtime-benchmarks = ['mv-node-runtime/runtime-benchmarks', 'polkadot-service/runtime-benchmarks']
